[profile.default]
src = "src"
out = "out"
libs = ["lib", "node_modules"]
test = "src/test"
solc = "0.8.6"
optimizer = true
optimizer_runs = 200

remappings = [
    "forge-std/=lib/forge-std/src/",
    "@openzeppelin/=node_modules/@openzeppelin/",
    "../node_modules/@openzeppelin/=node_modules/@openzeppelin/",
]

[profile.default.fuzz]
runs = 256

[fmt]
line_length = 120
tab_width = 4
bracket_spacing = false
